language: rust
rust:
  - stable
  - beta
  - nightly
os:
  - linux
  - osx

script:
  # Ensure that we build without warnings.
  - cd rust_src
  - cargo build --features "strict"
  - cd ..

  # Configure Emacs for building
  - ./autogen.sh
  # TODO: set up makeinfo on travis.
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then ./configure --without-makeinfo --with-xpm=no --with-gif=no --with-gnutls=no LDFLAGS="-Wl,-undefined,error" ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./configure --without-makeinfo --with-xpm=no --with-gif=no LDFLAGS="-Wl,--no-undefined" ; fi
  - make -j 3

  - make check || echo 'make check failed'

notifications:
  fast_finish: true
  email: false

matrix:
  allow_failures:
    - rust: nightly
    - os: osx
